# Generated by Django 2.2.4 on 2020-11-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
