# Generated by Django 2.2.4 on 2020-12-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sender',
        ),
        migrations.AddField(
            model_name='comment',
            name='receiver',
            field=models.IntegerField(null=True),
        ),
    ]
