# Generated by Django 2.2.4 on 2020-12-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201201_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mention',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
