# Generated by Django 2.2.4 on 2020-12-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201201_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mention',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
