# Generated by Django 2.2.4 on 2020-12-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201201_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mention',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
