# Generated by Django 2.2.4 on 2020-12-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201201_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mention',
            new_name='mentions',
        ),
    ]
