# Generated by Django 2.2.4 on 2020-12-01 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201201_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mentions',
        ),
    ]
