# Generated by Django 2.2.4 on 2020-12-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_userprofile_mentions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mentions',
        ),
        migrations.AddField(
            model_name='comment',
            name='rec_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
